version: '3.8'

services:
  backend:
    build: ./helper-backend
    command: gunicorn helper_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=helper_pg_user
      - POSTGRES_PASSWORD=helper_hard_pass
      - POSTGRES_DB=HelperDB
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data: